### ISSUE TITLE
Print button after order

### ISSUE THREAD

**Issue by LEstefano** [kilbot/WooCommerce-POS#236]
Hi @kilbot kilbot, @thomasmery thomasmery, @michaelirick 

I am using the POS and it is great, but it is failling when I try to print the receipt. There is a button (and also the option to print it directly on the plugin settings) but when I click it raises a error because the cross origin permission. It is due to the load of cndjs backbone.radio libraries. 

I tried different plugins to allow to reach these kind of URLs, but no luck for the moment. Also I checked it in different browsers and it is the same for me. I am using the free version. 

Do you know if any other facing this issue? Any possible solution?

Here the console log: 

> app.min.js?ver=0.4.24:1 Uncaught DOMException: Blocked a frame with origin "https://www.xxxxxx.es" from accessing a cross-origin frame.
>     at n.init (https://www.xxxxxx.es/wp-content/plugins/woocommerce-pos/assets/js/app.min.js?ver=0.4.24:1:175608)
>     at n.print (https://www.xxxxxx.es/wp-content/plugins/woocommerce-pos/assets/js/app.min.js?ver=0.4.24:1:175366)
>     at Object.u._callHandler (https://cdnjs.cloudflare.com/ajax/libs/backbone.radio/1.0.2/backbone.radio.min.js:2:1326)
>     at u.Channel.request (https://cdnjs.cloudflare.com/ajax/libs/backbone.radio/1.0.2/backbone.radio.min.js:2:1981)
>     at Object.u.<computed> [as request] (https://cdnjs.cloudflare.com/ajax/libs/backbone.radio/1.0.2/backbone.radio.min.js:2:3222)
>     at n.print (https://www.xxxxxx.es/wp-content/plugins/woocommerce-pos/assets/js/app.min.js?ver=0.4.24:1:215336)
>     at _ (https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.2.3/backbone-min.js:1:4060)
>     at m (https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.2.3/backbone-min.js:1:3728)
>     at f (https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.2.3/backbone-min.js:1:1563)
>     at n.l.trigger (https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.2.3/backbone-min.js:1:3608)
> 
> 
> init  | app.min.js?ver=0.4.24:1
> -- | -- | --
>   | print | app.min.js?ver=0.4.24:1
>   | u._callHandler | backbone.radio.min.js:2
>   | request | backbone.radio.min.js:2
>   | u.<computed> | backbone.radio.min.js:2
>   | print | app.min.js?ver=0.4.24:1
>   | _ | backbone.js:371
>   | m | backbone.js:356
>   | f | backbone.js:155
>   | l.trigger | backbone.js:346
>   | action | app.min.js?ver=0.4.24:1
>   | r | lodash.min.js:26
>   | dispatch | jquery.js:4435
>   | r.handle | jquery.js:4121

Thank you in advance

Kind regards

**Comment by LEstefano** [comment]
Hi again, 

I saw it is working on your demo instance, but I cannot check the plugin, nor the WP versions, nor which plugins are active there. 

Thank you in advance

Kind regards

**Comment by LEstefano** [comment]
Hi, 

this issue can be closed as it was a conflict with another plugin. 

Thank you

Kind regards,
Luis
